### ISSUE TITLE
Can't get the joint_states topic

### ISSUE THREAD

**Issue by Joy-Zhang-0303** [openspur/ypspur_ros#105]
@at-wat @DaikiMaekawa  @nhatao  @Taka-Kazu  @seiga-k 
Hello, eveyone, 
I'm using ypspur_ros to work with two-wheel-robot, however I Can't get the joint_states topic after launching robot.
I need your help about how to get the joint_states topic, because I need to monitor the rotating wheel tf using rviz.

My launch file is as below: 
```
<?xml version="1.0"?>
<launch>

  <arg name="port" default="/dev/tkb_motor_driver"/>
  <arg name="param_file" default="$(find project_tc)/param/sir_mk2.param"/>

  <node name="ypspur_ros" pkg="ypspur_ros" type="ypspur_ros">
    <param name="compatible" value="1" type="int"/>
    <param name="port" value="$(arg port)" type="str"/>
    <param name="param_file" value="$(arg param_file)" type="str"/>
    <param name="cmd_vel_expire" value="-1.0" type="double"/>
    <param name="odom_id" value="odom" type="str"/>
    <param name="base_link_id" value="base_link" type="str"/>
    <param name="hz" value="200.0" type="double"/>
    <param name="odometry_mode" value="diff" type="str"/>
    <param name="max_joint_id" value="32" type="int"/>
    <param name="vel" value="1" type="double"/>
    <param name="acc" value="1" type="double"/>
    <param name="angvel" value="3.14" type="double"/>
    <param name="angacc" value="3.14" type="double"/>
    <!--remap from="/tf" to="/tf_ypspur_ros"/-->
    <remap from="/tf" to="/tf"/> 
  </node>

</launch>

```
![Screenshot from 2022-10-26 19-06-52](https://user-images.githubusercontent.com/48177679/197998963-c7d620ed-5dab-4a70-a5ae-1855b41c894d.png)

**Comment by Joy-Zhang-0303** [comment]
@at-wat 
Hi, Watanabe-san, 
It will be very helpful if you can give some advices. Cuttently,  the Robot Hardware is optimized using T-Frog i-Cart-Mid. 
(2-axis Blushless Motor Driver: tf-2md3-r6)

**Comment by seiga-k** [comment]
You need to set ```joint?_enable``` parmeter to enable to get JointState topic. Set axis number to ```?``` as you like.
https://github.com/openspur/ypspur_ros/blob/master/doc/ypspur_ros.md#joint_enable-bool-false

**Comment by Joy-Zhang-0303** [comment]
> You need to set ```joint?_enable``` parmeter to enable to get JointState topic. Set axis number to ```?``` as you like.
> 
> https://github.com/openspur/ypspur_ros/blob/master/doc/ypspur_ros.md#joint_enable-bool-false
> 
> 

@seiga-k 
Hello, Seiga-San,

Thanks so much for your advice. I have got the joint state topic as you said .
